# Generated by Django 5.2.7 on 2025-10-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='Facility_bed',
            new_name='facility_bed',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='Hopspital_name',
            new_name='hospital_name',
        ),
    ]
